### ISSUE TITLE
Can't build with node 6.2.2/npm 3.9.5 on Mac OS 10.11.5

### ISSUE THREAD

**Issue by jbrains** [rhysd/Stream#3]
I'm really excited about this project. Sadly, I can't build it.

This fails:

```
tsc --pretty -p renderer && browserify renderer/js -o build/renderer.js
```

I've attached the relevant [npm-debug.log.zip](https://github.com/rhysd/YourFukurou/files/321438/npm-debug.log.zip)

The build failure details:

```

> yourfukurou@0.0.0 build /Users/jbrains/Workspaces/YourFukurou
> npm run build-main && npm run build-renderer


> yourfukurou@0.0.0 build-main /Users/jbrains/Workspaces/YourFukurou
> tsc --pretty -p main


> yourfukurou@0.0.0 build-renderer /Users/jbrains/Workspaces/YourFukurou
> tsc --pretty -p renderer && browserify renderer/js -o build/renderer.js


[100;30m36[0m             ReactPerf.printWasted();
[100;30m  [0m [91m            ~~~~~~~~~~~~~~~~~~~~~~~[0m

renderer/index.tsx(36,13): [91merror[0m TS2346: Supplied parameters do not match any signature of call target.


[100;30m39[0m             ReactPerf.printInclusive();
[100;30m  [0m [91m            ~~~~~~~~~~~~~~~~~~~~~~~~~~[0m

renderer/index.tsx(39,13): [91merror[0m TS2346: Supplied parameters do not match any signature of call target.


[100;30m42[0m             ReactPerf.printExclusive();
[100;30m  [0m [91m            ~~~~~~~~~~~~~~~~~~~~~~~~~~[0m

renderer/index.tsx(42,13): [91merror[0m TS2346: Supplied parameters do not match any signature of call target.


[100;30m45[0m             ReactPerf.printOperations();
[100;30m  [0m [91m                      ~~~~~~~~~~~~~~~[0m

renderer/index.tsx(45,23): [91merror[0m TS2339: Property 'printOperations' does not exist on type 'typeof Perf'.
```

**Comment by jbrains** [comment]
I'm just making notes as I discover things...

**Comment by jbrains** [comment]
It looks like this would work with ReactPerf in this commit from June 6, 2016: https://github.com/facebook/react/commit/d101fa68bce34a62613a3e86981266111e8950267#diff-9bb40ed30e3dd21208c7f4d8ac0a7588

Since that commit, the `print*()` functions now _require_ a `Measurements` parameter. It looks maybe like we could invoke `getLastMeasurements()` to get a suitable `Measurements` object, but I'm literally just lining up types and hoping for the best.

**Comment by jbrains** [comment]
Nope. I tried to find a version of React with which this code would work, and decided that 2 hours was enough time to just flail around.

I tried invoking `getLastMeasurements()` and passing that value to each of the `print*()` functions, but...

```
> yourfukurou@0.0.0 build-renderer /Users/jbrains/Workspaces/YourFukurou
> tsc --pretty -p renderer && browserify renderer/js -o build/renderer.js


47             ReactPerf.printOperations(lastMeasurements);
                         ~~~~~~~~~~~~~~~

renderer/index.tsx(47,23): error TS2339: Property 'printOperations' does not exist on type 'typeof Perf'.
```

I'm staring the function `printOperations()` in the face. I see it. It's there. I don't know why Typescript's type checker can't see it. There is too much spaghetti for my brain right now. Can anyone else see the problem?

**Comment by rhysd** [comment]
Yes, currently `react-addons-perf.d.ts` in DefinitelyTyped is old.  

https://github.com/DefinitelyTyped/DefinitelyTyped/pull/9662

For now, please replace `typings/globals/react-addons-perf/index.d.ts` with [this file](https://raw.githubusercontent.com/rhysd/DefinitelyTyped/f12a6775e2064deed1600c6bb3e3a0a678ca2e97/react/react-addons-perf.d.ts).  Please do not forget removing `/// <reference path="react.d.ts" />` from the source.

**Comment by jbrains** [comment]
Thanks. I could not, for the life of me, figure out what I was depending on that was out of date.

I don't know DefinitelyTyped yet, but it looks like some kind of massive database of ADT/interface/protocol definitions for well-known projects. Interesting.

I would prefer to temporarily depend on your fork of DefinitelyTyped, then switch back when they accept your pull request. I hope that works, because I'm planning to try it... but that's not how things work at all, so I'll go with your solution. :) Thanks.

**Comment by rhysd** [comment]
In typings, a TypeScript's type definition file manager, it deals with DefinitelyTyped as special source of type definitions.  So, I don't know how I can use my fork temporarily. (Sorry, I'm also not familiar with typings.)

So, as I described, please replace type definition file.  It's direct and exact way to build this app correctly for now.  On the PR merged, I'll update `typings.json` as soon as possible.

**Comment by jbrains** [comment]
Understood. Thanks.

**Comment by rhysd** [comment]
I'll ping you when the PR is merged and app is ready to be built.

**Comment by rhysd** [comment]
@jbrains 

The PR merged and I updated type definitions.  Please reinstall type definition files.

```
$ git pull
$ rm -r ./typings
$ ./node_modules/.bin/typings install
$ npm run build
```
